<?php 
    if (!isset($_SESSION)) {
        session_start();
    }
    $email = $_SESSION['email'];
    // unset($_SESSION['email']);
?>
<span style="font-weight: 400;">Página resultado de busca do imóvel ideal</span>

<?php

// V795, loteamento-lagoa-park
$lista_prod = $this->getImoveisSelecionados($email); 
$is_first=true;
$lista_sku="";
$flag_sem_imovel = false;
foreach($lista_prod as $item){
    if(intval($item['id_imovel']) == 0){
        $flag_sem_imovel = true;
        break;
    }
    $_product = $this->getProductById(intval($item['id_imovel']));
    if($is_first){
        $lista_sku .= $_product->getSku();
        $is_first=false;
    }else{
        $lista_sku .= ', '.$_product->getSku();
    }
}

if(!$flag_sem_imovel){
    $productsBlock = $this->getLayout()->createBlock(\Magento\CatalogWidget\Block\Product\ProductsList::class);
    $productsBlock->setProductsCount(count($lista_prod));
    $productsBlock->setTemplate("product/widget/content/grid.phtml");
    $productsBlock->setConditionsEncoded("^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`()`,`value`:`".$lista_sku."`^]^]");
    echo $productsBlock->toHtml();
}else{
    echo "<h2>Não achamos imóveis adequados para a sua pesquisa.</h2>";
}
?>

<!-- {{widget type="Magento\CatalogWidget\Block\Product\ProductsList"
    show_pager="0"
    products_count="10"
    template="Magento_CatalogWidget::product/widget/content/grid.phtml"
    conditions_encoded="^[`1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Combine`,`aggregator`:`all`,`value`:`1`,`new_child`:``^],`1--1`:^[`type`:`Magento||CatalogWidget||Model||Rule||Condition||Product`,`attribute`:`sku`,`operator`:`==`,`value`:`residencial-pedra-branca, sobrado-pinguirito`^]^]"}}
 -->

<style>
.product-item-actions {
    display: none;
}
</style>

