<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <?php endif; ?>
        <div class="actions">
            <div class="buttons-contato">
                <a class="a-contato-whats" href="https://wa.me/5548996149358">
                    <span>
                        <img src="<?php echo $block->getUrl("pub/media/icons/")?>bolha-de-bate-papo.png"/>
                        Fala conosco no Whatsapp!
                    </span>
                </a>
                <a class="a-contato-numero" href="https://wa.me/5548996149358">
                    <span>
                        Ligue para nós 
                        (48) 99614-9358
                    </span>
                </a>
                <a class="a-contato-email" href="https://wa.me/5548996149358">
                    <span>
                        Mande um email
                        santinoncorretora@gmail.com
                    </span>
                </a>
            </div>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

