<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php if ($_product->isSaleable()) :?>
<div class="box-tocart">
    <div class="fieldset">
        <?php if ($block->shouldRenderQuantity()) :?>
        <?php endif; ?>
        <div class="actions">
            <div class="buttons-contato">
                <a class="a-contato-whats" href="https://wa.me/5548996149358">
                    <span>
                        <img src="<?php echo $block->getUrl("pub/media/icons/")?>whatsapp.png"/>
                        Fale conosco no Whatsapp!
                    </span>
                </a>
                <a class="a-contato-numero" href="https://wa.me/5548996149358">
                    <span>
                        Ligue para nós 
                        (48) 99614-9358
                    </span>
                </a>
                <a class="a-contato-email" href="https://wa.me/5548996149358">
                    <span>
                        Mande um email
                        santinoncorretora@gmail.com
                    </span>
                </a>
            </div>
            <?= $block->getChildHtml('', true) ?>
        </div>
    </div>
</div>
<?php endif; ?>

<style>
a.a-contato-whats {
    padding: 1% 3%;
    font-size: 20px;
    border: #505443 2px solid;
    border-radius: 50px;
    width: 380px;
    /* display: flex;
    justify-content: center; */
    color: #FFFFFF;
    background: #25D366;
}
a.a-contato-whats:hover {
    background: lightgreen;
}
.buttons-contato {
    display: grid;
    justify-items: center;
}
a.a-contato-whats span {
    display: flex;
    align-items: center;
}
a.a-contato-whats img {
    width: 60px;
}
a.a-contato-whats span {
    display: flex;
    align-items: center;
    justify-content: space-evenly;
}
.buttons-contato a {
    margin-bottom: 2%;
}
</style>