<?php 
$baseUrl = $block->getBaseUrl();
$baseUrl = explode('default/', $baseUrl);
$baseUrl = $baseUrl[0];
?>
<footer class="page-footer">
    <div class="row">
        <div class="footer-col">
            <ul>
                <li><a href="#">(48)99940-4105</a></li>
                <li><a href="#">rafaelfagundes64@gmail.com</a></li>
                <li><a href="#">Rua Manoel Álvaro de Araújo, 18<br>Garopaba - SC</a></li>
            </ul>
        </div>
    </div>
</footer>