<?php 
$baseUrl = $block->getBaseUrl();
$baseUrl = explode('default/', $baseUrl);
$baseUrl = $baseUrl[0];
?>
<footer class="page-footer">
    <div class="row">
        <div class="footer-col">
            <a href="<?php echo $block->getBaseUrl();?>"> 
                <img class='logo-footer' src="<?php echo $block->getLayout()->getBlock('logo')->getLogoSrc(); ?>" alt="Júlia imóveis">
            </a>
        </div>
        <div class="footer-col">
            <label class="titulo">Contato</label>
            <label href="#">(48) 99940-4105</label>
        </div>
        <div class="footer-col">
            <label class="titulo">Email</label>
            <label href="#">juliasantinon@gmail.com</label>
        </div>
        <div class="footer-col">
            <label class="titulo">Endereço</label>
            <label href="#">Rua Manoel Álvaro de Araújo, 18, Garopaba - SC</label>
        </div>
    </div>
</footer>

<style>
label.titulo {
    color: #c49164;
}
.footer-col{
    display: grid;
}
</style>